var config = {
    domain: 'account2.ivantus.ru',//location.hostname + ( location.port ? ':' + location.port: ''),
    needReloadAfterAuth: false,
    pageRegisterSite: 'SiteManager/RegisterSite',
	translate: {},

    classDialogAddFilter: 'ManAcc.dialog.addFilter',
    classDialogChooseCrossReportBlock: 'ManAcc.dialog.chooseCrossReportBlock',
    classDialogDataInputConfiguration: "ManAcc.dialog.DataInputConfiguration",
    
    classDialogFlatReportColumn: 'ManAcc.dialog.FlatReportColumn',
    classDialogFlatReportRow: 'ManAcc.dialog.FlatReportRow',
    classDialogMakeReportOrder: 'ManAcc.dialog.MakeReportOrder',
    classDialogReportParameter: 'ManAcc.dialog.ReportParameter',
    classDialogReportQueue: "ManAcc.dialog.ReportQueue",
    classDialogReportQueue: 'ManAcc.dialog.ReportQueue',
    classDialogReportView: 'ManAcc.dialog.ReportView',
    classDialogSelectClassForSimpleAddReportDelimiter: 'ManAcc.dialog.selectClassForSimpleAddReportDelimiter',
    classDialogSelectDataSource: 'ManAcc.dialog.selectDataSource',
    classDialogSelectReportConfiguration: 'ManAcc.dialog.selectReportConfiguration',
    classDialogSimpleDelimiterByAlgorithm: 'ManAcc.dialog.simpleDelimiterByAlgorithm',
    classDialogSimpleDelimiterByClass: 'ManAcc.dialog.simpleDelimiterByClass',
    classDialogSimpleDelimiterByDate: 'ManAcc.dialog.simpleDelimiterByDate',
    classDialogSimpleDelimiterByDictionary: 'ManAcc.dialog.simpleDelimiterByDictionary',
    classDialogSimpleDelimiterEmpty: 'ManAcc.dialog.simpleDelimiterEmpty',
    classFormAuth: "ManAcc.forms.formAuth",
    classFormChooseDictionaryFilterRecords: "ManAcc.forms.formChooseDictionaryFilterRecords",
    classFormChooseDictionaryRecord: "ManAcc.forms.formChooseDictionaryRecord",
    classFormChooseRecordClass: "ManAcc.form.ChooseRecordClass",
    classFormClassEdit: "ManAcc.forms.formClassEdit",
    classFormDataInputMenu: "ManAcc.forms.formDataInputMenu",
    classFormDataInputRecord: "ManAcc.forms.formDataInputRecord",
    classFormDataInputView: "ManAcc.forms.formDataInputView",
    classFormDictionaryEdit: "ManAcc.forms.formDictionaryEdit",
    classFormDictionaryMenu: "ManAcc.forms.formDictionaryMenu",
    classFormDictionaryPropertyType: "ManAcc.forms.formDictionaryPropertyType",
    classFormPrivileges: "ManAcc.forms.formPrivileges",
    classFormPropertyValue: "ManAcc.forms.formValueDialog",
    classFormRegisterClient: "ManAcc.forms.formRegisterClient",
    classFormUser: "ManAcc.forms.formUser",
    classMenuReporting: "ManAcc.menu.Reporting",
    classPanelBindedFilter: "ManAcc.panel.BindedFilter",
    classPanelReportBlockAlgorithm: "ManAcc.window.ReportBlockAlgorithm",
    classPanelReportParamList: "ManAcc.panel.ReportParamList",
    classPanelTreeReportDividers: "ManAcc.panel.TreeReportDividers",
    classWindowBindedFiltersList: "ManAcc.window.BindedFiltersList",
    classWindowDataInputSetFilterValue: "ManAcc.forms.windowDataInputSetFilterValue",
    classWindowReportBlockAlgorithmsList: "ManAcc.window.ReportBlockAlgorithmsList",
    classWindowReportConfiguration: "ManAcc.window.ReportConfiguration",	
	classFormChooseRecord: "ManAcc.panel.TreePanel",
 

    lang: {
        "ru" : "Русский",
        "en" : "English"
    }
};